web:
  build: .
  command: node server.js
  environment:
    - REDIS_URL
  ports:
    - 5000:8080
  links:
    - redis

worker:
  command: node worker.js
  environment:
    - REDIS_URL
  build: .
  links:
    - redis

redis:
  image: convox/redis
  ports:
    - 6379
